version: "3.3"
services:
  backend:
    image: fastapi-backend:latest
    env_file:
      - .env
    environment:
      - ENVIRONMENT=TEST
    build:
      context: ./backend
      dockerfile: ../../fastapi-test/backend/app/backend.dockerfile
    container_name: fastapi-backend
    ports:
    - 8083:80
